version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"    
    restart: always
    env_file:
      - .env
    volumes:
      - multitenant-api:/var/lib/postgresql/data
    ports:
      - '5433:5433'
volumes:
  multitenant-api:
